-- liquibase formatted sql

-- changeset Homychok:1
CREATE TABLE avatar (
                        avatar_id         BIGINT PRIMARY KEY,
                        data       BYTEA,
                        file_path  VARCHAR(255),
                        file_size  BIGINT,
                        media_type VARCHAR(255),
                        student_id BIGINT REFERENCES student (student_id)
);

ALTER TABLE avatar ALTER COLUMN avatar_id ADD GENERATED BY DEFAULT AS IDENTITY;